# Generated by Django 5.0.1 on 2025-01-14 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.BigIntegerField()),
                ('email', models.EmailField(max_length=120)),
                ('tipo_usuario', models.CharField(choices=[('AL', 'Aluno'), ('VT', 'Visitante')], default='AL', max_length=2)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=15)),
                ('tipo_dispositivo', models.CharField(choices=[('PC', 'Computador'), ('CT', 'Catraca')], default='CT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.usuario')),
                ('matricula', models.CharField(max_length=15)),
                ('curso', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pages.usuario',),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.usuario')),
                ('departamento', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pages.usuario',),
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.usuario')),
                ('motivo_visita', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pages.usuario',),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.usuario')),
            ],
        ),
    ]
