# Generated by Django 5.1.4 on 2025-01-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_aluno_matricula_alter_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='situacao_matricula',
            field=models.CharField(choices=[('Deferida', 'Deferida'), ('Indeferida', 'Indeferida')], default='Deferida', max_length=10),
        ),
    ]
