# Generated by Django 5.1.4 on 2025-01-30 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_aluno_situacao_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='dispositivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.dispositivo'),
        ),
    ]
