# Generated by Django 5.1.4 on 2025-01-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_entrada_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.dispositivo'),
        ),
    ]
